# Generated by Django 4.2.1 on 2023-05-29 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TasksAPP', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task_description',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
